# Generated by Django 3.0.4 on 2020-03-17 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='mysqlImage',
            fields=[
                ('mid', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('letters', models.CharField(max_length=100)),
                ('isdelete', models.IntegerField(default=0)),
                ('addtime', models.DateTimeField(auto_now_add=True)),
                ('modifytime', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'tb_ocr_letters',
            },
        ),
    ]
